# Generated by Django 5.0.3 on 2024-03-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=20)),
                ('country', models.TextField(max_length=20)),
                ('language', models.TextField(max_length=20)),
                ('province', models.TextField(max_length=20)),
                ('data_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
